version: "3"
services:
  nest:
    build:
      context: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    environment:
      TYPEORM_PASSWORD: "${TYPEORM_PASSWORD}"
      TYPEORM_USERNAME: "${TYPEORM_USERNAME}"
      TYPEORM_DATABASE: "${TYPEORM_DATABASE}"
      TYPEORM_HOST: "db" 
      TYPEORM_PORT: ${TYPEORM_PORT}
      SERVER_PORT: ${SERVER_PORT}
    command: yarn start
  db:
    image: "postgres:12-alpine"
    restart: always
    ports:
      - "${TYPEORM_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${TYPEORM_PASSWORD}"
      POSTGRES_USER: "${TYPEORM_USERNAME}"
      POSTGRES_DB: "${TYPEORM_DATABASE}"
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
